#!/bin/sh

which autoconf
if ! test $? -eq 0
then
  echo "error, install autoconf"
  exit 1
fi

which automake
if ! test $? -eq 0
then
  echo "error, install automake"
  exit 1
fi

which libtool || which libtoolize
if ! test $? -eq 0
then
  echo "error, install libtool"
  exit 1
fi

which pkg-config
if ! test $? -eq 0
then
  echo "error, install pkg-config"
  exit 1
fi

touch configure.ac
touch NEWS
touch AUTHORS
touch README
touch ChangeLog
autoreconf -fvi
