name: "🕷️ Bug report"
description: Report errors or unexpected behavior
labels:
  - "bug"
body:
  - type: markdown
    attributes:
      value: |
        Before submitting a bug, read the [FAQ](https://github.com/neutrinolabs/xrdp/wiki/Tips-and-FAQ).
        **In particular, on systemd-based systems. make sure you are not logged in on the console as the same user you are trying to use for xrdp**
  - type: input
    attributes:
      label: xrdp version
      placeholder: 0.9.20
    validations:
      required: true
  - type: textarea
    attributes:
      label: Detailed xrdp version, build options
      description: Copy & paste the result of `xrdp --version`. DO NOT remove `~~~` but paste the result between two `~~~`.
      value: |
        ~~~
        PASTE HERE
        ~~~
  - type: input
    attributes:
      label: Operating system & version
      placeholder: "Ubuntu 22.04 / AlmaLinux 9 / FreeBSD 13.2 / etc"
      description: Tell us about your operating system. See PRETTY_NAME
        in /etc/os-release if you don't know.

        Note we are currently unable to provide direct support for Red Hat
        Enterprise Linux. Either reproduce the issue on CentOS/Alma/Rocky
        OS, or contact Red Hat directly for support.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Installation method
      description: How was xrdp installed from?
      options:
        - dnf / apt / zypper / pkg / etc
        - Homebrew / MacPorts
        - git clone & make install
        - Doesn't matter
        - other
    validations:
      required: true
  - type: input
    attributes:
      label: Which backend do you use?
      description: Tell us about xrdp backend and version you're using. Typically, it would be either Xvnc or xorgxrdp or rarely NeutrionRDP / FreeRDP.
      placeholder: Xvnc (tigervnc-1.12.0-13.el9_2)
  - type: input
    attributes:
      label: What desktop environment do you use?
      description: Tell us about your desktop (e.g. GNOME / KDE / Xfce / xterm). If you're certain the bug you about to report is not desktop specific, fill "any" here.
      placeholder: GNOME
  - type: input
    attributes:
      label: Environment xrdp running on
      description: Tell us whether xrdp is running on a VM, or if on a physical machine what graphics cards are installed.
  - type: input
    attributes:
      label: What's your client?
      description: If you issue occurs with specific clients, tell us the client app name, app version client os version and platform.
      placeholder: Microsoft's official client from Mac App Store, running on macOS Ventura.
  - type: dropdown
    attributes:
      label: Area(s) with issue?
      description: What things had an issue? Check all that apply.
      multiple: true
      options:
        - Audio redirection
        - Authentication
        - Crashes such as segfault
        - Clipboard
        - Compatiblity aginst clients
        - Compile error
        - File transfer / drive redirection
        - Graphic glitches
        - Keyboard / Mouse
        - Network
        - Performance
        - Session manager (sesman)
        - Smartcard
        - Other
  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: Having detailed steps helps us reproduce the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✔️ Expected Behavior
      placeholder: What were you expecting?
    validations:
      required: false
  - type: textarea
    attributes:
      label: ❌ Actual Behavior
      placeholder: What happened instead?
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: Links? References? Anything that will give us more context about the issue you are encountering!  We recommend attaching `xrdp.log`, `xrdp-sesman.log`, `xrdp/xorg.conf` or screenshots to clarify context.
