#!/bin/sh -e

if ! ([ "$1" = "configure" ] || [ "$1" = "reconfigure" ]); then
  exit 0
fi


XRDP="xrdp"
CHOWN="/bin/chown"
ADDUSER="/usr/sbin/adduser"
SESMANLOG="/var/log/xrdp-sesman.log"

[ -d /var/run/xrdp ] || mkdir -p /var/run/xrdp
$ADDUSER --system --disabled-password --disabled-login --home /var/run/xrdp \
         --no-create-home --quiet --group $XRDP

touch $SESMANLOG
$CHOWN $XRDP:$XRDP $SESMANLOG


#DEBHELPER#
