#!/bin/sh

DN=$1

if [ "${DN}" != "" ] && [ -d /tmp/.xrdp ] && [ "$DN" -ge 10 ] && [ "$DN" -le 99 ] ; then

	if [ -f /tmp/.X${DN}-lock ] ; then
		DNO=`stat -c %U /tmp/.X${DN}-lock`
		if [ "${DNO}" != "${USER}" ] ; then
			echo It is not allowed to remove a session from another user, namely ${DNO}
			exit -1
		fi

		echo Start removing session for display $DN

		rm -ri \
			/tmp/.xrdp/xrdpapi_${DN} \
			/tmp/.xrdp/xrdp_chansrv_audio_socket_${DN} \
			/tmp/.xrdp/xrdp_disconnect_display_${DN} \
			/tmp/.xrdp/xrdp_display_${DN} \
			/tmp/.X${DN}-lock \
			/tmp/.X11-unix/${DN}

		find /tmp/.xrdp -maxdepth 1 -user ${USER} -exec rm -ri {} \;
		find /tmp/.ICE-unix -maxdepth 1 -user ${USER} -exec rm -ri {} \;
	else
		echo Not a valid display since there is no /tmp/.X${DN}-lock lock file
	fi
else
	echo Display should be between 10 and 99, not ${DN}
fi
