#!/bin/sh

if [ "`id -u`" != "0" ] ; then
	echo Only root can execute this.
	exit 1
fi

# Start with reaping the old sessions
echo Reap dead xrdp sessions first
if [ -x /usr/sbin/xrdp-reap-sessions ] ; then
	/usr/sbin/xrdp-reap-sessions
fi

echo Kill all existing active sessions which are left
for X in $(ls /tmp/.X??-lock)
do
	OWNER=`stat -c %U ${X}`
	echo Attempting to stop server with lock held on ${X} owned by ${OWNER}
	(su ${OWNER} -c xrdp-kill)
done
