#!/bin/bash

if [ "${DISPLAY}" != "" ] || [ "${DBUS_SESSION_BUS_ADDRESS}" != "" ] ; then
	echo You should not connect from an existing X sesion to kill your xrdp session.
	echo To kill your current session use eg gnome-session-quit directly
	exit 1
fi

compatiblePrograms=( nautilus kdeinit kded4 pulseaudio trackerd )

# Attempt to get a program pid
for index in ${compatiblePrograms[@]}; do
	PIDS=$(pidof -s ${index})
	for PID in ${PIDS}
	do
		if [[ "${PID}" != "" ]]; then
			DISPLAY=$(tr '\0' '\n' < /proc/${PID}/environ | grep "DISPLAY" | cut -d "=" -f 2-)
			DISP=$(echo ${DISPLAY} | cut -f 1 -d "." | cut -c 2-)

			DNO=`stat -c %U /tmp/.X${DISP}-lock`
			if [ "${DNO}" != "${USER}" ] ; then
				echo It is not allowed to kill a session from another user, namely ${DNO}, skipping this one
			else
				if [ "${DISP}" -ge 10 ] && [ "${DISP}" -le 99 ] ; then
					export DISPLAY
					break
				fi
			fi
			DISPLAY=""
		fi
		if [ "${DISPLAY}" != "" ] ; then
			# valid display, so a valid session
			break
		fi
		PID=""
	done
done

if [[ "${PID}" == "" ]]; then
	echo "Could not detect active login session"
	exit 1
fi

QUERY_ENVIRON="$(tr '\0' '\n' < /proc/${PID}/environ | grep "DBUS_SESSION_BUS_ADDRESS" | cut -d "=" -f 2-)"
if [[ "${QUERY_ENVIRON}" != "" ]]; then
	export DBUS_SESSION_BUS_ADDRESS="${QUERY_ENVIRON}"
	echo "Connected to session:"
	echo "DBUS_SESSION_BUS_ADDRESS=${DBUS_SESSION_BUS_ADDRESS}"
	echo "DISPLAY=${DISPLAY}"
else
	echo "Could not find dbus session ID in user environment."
	exit 1
fi

if [ -x /usr/bin/gnome-session-quit ] ; then
	gnome-session-quit --logout --no-prompt
fi
