#!/bin/bash

if [ "`id -u`" != "0" ] ; then
	echo Only root can execute this.
	exit 1
fi

if [ ! -d /tmp/.xrdp ] ; then
	echo No xrdp running, holding no sockets in /tmp/.xrdp
	exit 1
fi

for f in $(ls /tmp/.X??-lock 2>/dev/null)
do
	DN=${f: -2}
	if [ ! -f /tmp/.X${DN}-lock ] ; then
		echo Reaping display ${DN} since it holds no /tmp/.X${DN}-lock
		rm -rf \
			/tmp/.xrdp/xrdpapi_${DN} \
			/tmp/.xrdp/xrdp_chansrv_audio_socket_${DN} \
			/tmp/.xrdp/xrdp_disconnect_display_${DN} \
			/tmp/.xrdp/xrdp_display_${DN}
	fi
done
