#!/bin/bash

if [ "`id -u`" != "0" ] ; then
	echo Only root can execute this.
	exit 1
fi

if [ ! -d /tmp/.xrdp ] ; then
	echo No xrdp running, holding no sockets in /tmp/.xrdp
	exit 1
fi

DISPLAYS=""
PIDS=$(pidof gnome-session xfce4-session)
for PID in $(ls -1 /tmp/.ICE-unix/ 2>/dev/null)
do
	if [ "${PID}" != "" ] && [ "${PIDS}" != "" ] ; then
		RV=`echo "${PIDS}" | grep "${PID}"`
		if [ $? -eq 0 ] ; then
#			echo Skip /tmp/.ICE-unix/${PID} since this is an active session

			DISPLAY=$(tr '\0' '\n' < /proc/${PID}/environ | grep "DISPLAY" | cut -d "=" -f 2- | cut -f 1 -d "." | cut -c 2-)
			if [ "${DISPLAY}" -ge 10 ] && [ "${DISPLAY}" -le 99 ] ; then
				DISPLAYS="${DISPLAYS} ${DISPLAY} "
			fi
		else
			echo Remove /tmp/.ICE-unix/${PID} since its not alive anymore
			rm -f /tmp/.ICE-unix/${PID}
		fi
	fi
done

echo Start with active xrdp displays: ${DISPLAYS}
for LOCK in $(ls -1 /tmp/.X??-lock 2>/dev/null)
do
	if [ "${DISPLAYS}" == "" ] ; then
		echo Remove dead lock ${LOCK} since there are no active displays
		rm -f ${LOCK}
	else
		if [ "${LOCK}" != "" ] ; then
			RV=`echo "${DISPLAYS}" | grep " ${LOCK:7:2} "`
			if [ $? -ne 0 ] ; then
				echo Remove dead lock ${LOCK} since its not part of an active display
				rm -f ${LOCK}
			fi
		fi
	fi
done

echo Reap all pending sockets in /tmp/.xrdp which are not used anymore
for f in $(ls /tmp/.xrdp/xrdp*_?? 2>/dev/null)
do
	DN=${f: -2}
	if [ ! -f /tmp/.X${DN}-lock ] ; then
#		echo Reaping socket ${f} since it holds no /tmp/.X${DN}-lock
		rm -f ${f}
		rm -f /tmp/.X11-unix/X${DN}
	fi
done
