#!/bin/sh

if [ "`id -u`" != "0" ] ; then
	echo Only root can execute this.
	exit 1
fi

# Start with reaping the old sessions
echo Reap dead xrdp sessions first
if [ -x /usr/sbin/xrdp-reap-sessions ] ; then
	/usr/sbin/xrdp-reap-sessions
fi

echo Kill all existing active sessions which are left
for X in $(ls /tmp/.X??-lock 2>/dev/null)
do
	OWNER=`stat -c %U ${X}`
	echo Attempting to stop server with lock held on ${X} owned by ${OWNER}
	(su ${OWNER} -c xrdp-kill)
done

PROCS=$(pidof X11rdp Xvnc)
if [ "${PROCS}" != "" ] ; then
	echo Not all processes finished yet, waiting for them to finish
	sleep 3
fi

PROCS=$(pidof X11rdp Xvnc)
if [ "${PROCS}" != "" ] ; then
	kill ${PROCS}

	echo Waiting for all processes to finish
	sleep 3
	PROCS=$(pidof X11rdp Xvnc)
	if [ "${PROCS}" != "" ] ; then
		echo Not all processes finished, terminating them now
		kill -9 ${PROCS}
	fi
fi
