#!/bin/bash

compatiblePrograms=( nautilus kdeinit kded4 pulseaudio trackerd )

# Attempt to get a program pid
for index in ${compatiblePrograms[@]}; do
	PID=$(pidof -s ${index})
	if [[ "${PID}" != "" ]]; then
		DISPLAY=$(tr '\0' '\n' < /proc/${PID}/environ | grep "DISPLAY" | cut -d "=" -f 2-)
		DISP=$(echo ${DISPLAY} | cut -f 1 -d "." | cut -c 2-)
		if [ "${DISP}" -ge 10 ] && [ "${DISP}" -le 99 ] ; then
			export DISPLAY
			break
		fi
	fi
	PID=""
done

if [[ "${PID}" == "" ]]; then
	echo "Could not detect active login session"
	exit 1
fi

QUERY_ENVIRON="$(tr '\0' '\n' < /proc/${PID}/environ | grep "DBUS_SESSION_BUS_ADDRESS" | cut -d "=" -f 2-)"
if [[ "${QUERY_ENVIRON}" != "" ]]; then
	export DBUS_SESSION_BUS_ADDRESS="${QUERY_ENVIRON}"
	echo "Connected to session:"
	echo "DBUS_SESSION_BUS_ADDRESS=${DBUS_SESSION_BUS_ADDRESS}"
else
	echo "Could not find dbus session ID in user environment."
	exit 1
fi

gnome-session-quit --logout --no-prompt
