.\"                                      Hey, EMACS: -*- nroff -*-
.TH xrdp-keygen 8 "2007-07-31"
.SH NAME
xrdp-keygen \- xrdp RSA keys generation utility
.SH SYNOPSIS
.B xrdp-keygen
.RI [ options ]
.RI [ filename ]
.SH DESCRIPTION
This manual page documents briefly the command
.B xrdp-keygen.
.PP
\fBxrdp-keygen\fP generates the file 
.I /etc/xrdp/rsakeys.ini
whose contains the RSA keypair used to perform authentication to
the remote client. The public key is self-signed.
.SH OPTIONS
This program takes one option:
.TP
.B xrdp
Generate a new keypair. This is the option you should use.
.TP
.B test
Generate a test keypair. Do not use this option.
.SH SEE ALSO
.BR xrdp (8),
.BR sesman (8).
.SH AUTHOR
xrdp-keygen was written by Jay Sorg.
.PP
This manual page was written by Vincent Bernat <bernat@luffy.cx>,
for the Debian project (but may be used by others).
