.TH "xrdp-xcon" "8" "0.9.1" "xrdp team"
.SH NAME
xrdp\-xcon \- X11 event loop debugging helper for XRDP

.SH SYNOPSIS
.B xrdp\-xcon

.SH DESCRIPTION
.PP
\fBxrdp\-xcon\fP is a X application, which just opens a connection to the X server and polls for events.
It's pretty useless.

.SH SEE ALSO
.BR xev (1).
