.TH "xrdp\-sessvc" "8" "0.7.0" "xrdp team" ""
.SH "NAME"
xrdp\-sessvc \- \fBxrdp\fR session supervisor

.SH "SYNTAX"
.B xrdp\-sessvc
.I x_pid wm_pid

.SH "DESCRIPTION"
\fBxrdp\-sessvc\fR is the \fBxrdp\fR(8) session supervisor, which monitors the running X server and Windows Manager.
As soon as one of them quits, the other process is terminated as well.
.br
This program is only executed internally by \fBxrdp\-sesman\fP(8).

.SH "OPTIONS"
.TP
.I x_pid
The process ID of the forked X server to monitor.
.TP
.I wm_pid
The process ID of the forked Window Manager to monitor.

.SH "SEE ALSO"
.BR xrdp\-sesrun (8).

for more info on \fBxrdp\fR see http://www.xrdp.org/
