.TH "xrdp-dis" "8" "0.7.0" "xrdp team"
.SH NAME
xrdp\-dis \- xrdp disconnect utility

.SH SYNOPSIS
.B xrdp\-dis

.SH DESCRIPTION
.PP
\fBxrdp\-dis\fP is run with no parameters to disconnect your xrdp session.

.SH ENVIRONMENT
.TP
.B DISPLAY
to get the default host and display number.

.SH FILES
.TP
.I /tmp/.xrdp/xrdp_disconnect_display_*
UNIX socket used to communicate with the \fBxrdp\fP(8) session manager.

.SH SEE ALSO
.BR xrdp (1).
