name: build and test
on:
  push:
    branches-ignore:
      - "gh-pages"
    tags-ignore:
      - "v0.[0-8]**"
  pull_request:
    branches-ignore:
      - "gh-pages"

jobs:
  ci_on_freebsd:
    name: FreeBSD Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: test run
      uses: vmactions/freebsd-vm@v1
      with:
        disable-cache: true
        envs: |
          CPPFLAGS: "-I/usr/local/include"
          LDFLAGS: "-L/usr/local/lib "
        prepare: pkg install -y git autoconf automake libtool pkgconf opus jpeg-turbo fdk-aac pixman libX11 libXfixes libXrandr libxkbfile nasm fusefs-libs3 check imlib2 freetype2 cmocka ibus
        run: |
          ./bootstrap
          ./configure --localstatedir=/var --enable-strict-locations --with-pkgconfigdir=/usr/local/libdata/pkgconfig --enable-strict-locations --enable-ibus --enable-ipv6 --enable-opus --enable-jpeg --enable-fdkaac --enable-painter --enable-pixman --enable-fuse --with-imlib2 --with-freetype2
          make -j $(nproc || echo 4)
          make check
          make install
          /usr/local/sbin/xrdp -v
