name: build and test
on:
  push:
    branches-ignore:
      - "gh-pages"
    tags-ignore:
      - "v0.[0-8]**"
  pull_request:
    branches-ignore:
      - "gh-pages"

jobs:
  cppcheck:
    name: cppcheck
    runs-on: ubuntu-latest
    env:
      CC: gcc
      # This is required to use a version of cppcheck other than that
      # supplied with the operating system
      CPPCHECK_VER: "2.19.1"
      CPPCHECK_REPO: https://github.com/danmar/cppcheck.git
    steps:
      # Set steps.os.outputs.image to the specific OS (e.g. 'ubuntu20')
      - name: Get operating system name and version.
        id: os
        run: echo "image=$ImageOS" >>$GITHUB_OUTPUT
        shell: bash
      - uses: actions/checkout@v4
      - name: Cache cppcheck
        uses: actions/cache@v4
        env:
          cache-name: cache-cppcheck
        with:
          path: ~/cppcheck.local
          key: ${{ steps.os.outputs.image }}-build-${{ env.cache-name }}-${{ env.CPPCHECK_VER }}
      - run: sudo scripts/install_cppcheck_dependencies_with_apt.sh $CPPCHECK_VER
      - run: ./bootstrap
      - run: ./configure
      - run: scripts/install_cppcheck.sh $CPPCHECK_REPO $CPPCHECK_VER
      - run: scripts/run_cppcheck.sh -v $CPPCHECK_VER
